### PR TITLE
Influencer bio

### PR DESCRIPTION
**Pull request by naputami**
✅Add backend logic for influencer bio feature
✅Add migration and model for new table category_influencer
✅Set up and add route for testing influencer bio feature using postman

### CODE REVIEW

**Comment by evaneryanto** [comment]
Sip

**Review by evaneryanto — APPROVED** [review]
Thx You

**Comment by naputami** [comment]
[backend profile-bio](https://trello.com/c/9RVhbw99/10-backend-profile-bio)

**Comment by naputami** [comment]
[backend profile-bio](https://trello.com/c/9RVhbw99/10-backend-profile-bio)

**Pull request merged**
